name: ${project.name}
main: net.daboross.bukkitdev.costrepair.CostRepair
version: ${project.version}
author: Dabo Ross
description: Allows repairing at a cost
depend: [Vault]
commands:
  crepair:
    description: Repairs the item in your hand at a cost.
    usage: |
      To repair the item in your hand: /<command>
    permissions: costrepair.use
    aliases: [costrepair, repair, repairme]
